package com.maave.maps2go.modelo;
// Generated 30/03/2019 09:45:08 PM by Hibernate Tools 4.3.1



/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private int numComentario;
     private Marcador marcador;
     private Usuario usuario;
     private String contenido;
     private int likes;
     private int dislikes;

    public Comentario() {
    }

    public Comentario(int numComentario, Marcador marcador, Usuario usuario, String contenido, int likes, int dislikes) {
       this.numComentario = numComentario;
       this.marcador = marcador;
       this.usuario = usuario;
       this.contenido = contenido;
       this.likes = likes;
       this.dislikes = dislikes;
    }
   
    public int getNumComentario() {
        return this.numComentario;
    }
    
    public void setNumComentario(int numComentario) {
        this.numComentario = numComentario;
    }
    public Marcador getMarcador() {
        return this.marcador;
    }
    
    public void setMarcador(Marcador marcador) {
        this.marcador = marcador;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public int getLikes() {
        return this.likes;
    }
    
    public void setLikes(int likes) {
        this.likes = likes;
    }
    public int getDislikes() {
        return this.dislikes;
    }
    
    public void setDislikes(int dislikes) {
        this.dislikes = dislikes;
    }




}


