package com.maave.maps2go.modelo;
// Generated 30/03/2019 09:45:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable {


     private int numMarcador;
     private Tema tema;
     private String descripcion;
     private String datosUtiles;
     private double longitud;
     private double latitud;
     private Set comentarios = new HashSet(0);

    public Marcador() {
    }

	
    public Marcador(int numMarcador, Tema tema, String descripcion, double longitud, double latitud) {
        this.numMarcador = numMarcador;
        this.tema = tema;
        this.descripcion = descripcion;
        this.longitud = longitud;
        this.latitud = latitud;
    }
    public Marcador(int numMarcador, Tema tema, String descripcion, String datosUtiles, double longitud, double latitud, Set comentarios) {
       this.numMarcador = numMarcador;
       this.tema = tema;
       this.descripcion = descripcion;
       this.datosUtiles = datosUtiles;
       this.longitud = longitud;
       this.latitud = latitud;
       this.comentarios = comentarios;
    }
   
    public int getNumMarcador() {
        return this.numMarcador;
    }
    
    public void setNumMarcador(int numMarcador) {
        this.numMarcador = numMarcador;
    }
    public Tema getTema() {
        return this.tema;
    }
    
    public void setTema(Tema tema) {
        this.tema = tema;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getDatosUtiles() {
        return this.datosUtiles;
    }
    
    public void setDatosUtiles(String datosUtiles) {
        this.datosUtiles = datosUtiles;
    }
    public double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }
    public double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(double latitud) {
        this.latitud = latitud;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }




}


