package com.maave.maps2go.modelo;
// Generated 30/03/2019 09:45:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private String tipoTema;
     private Usuario usuario;
     private String color;
     private Set marcadors = new HashSet(0);

    public Tema() {
    }

	
    public Tema(String tipoTema, Usuario usuario, String color) {
        this.tipoTema = tipoTema;
        this.usuario = usuario;
        this.color = color;
    }
    public Tema(String tipoTema, Usuario usuario, String color, Set marcadors) {
       this.tipoTema = tipoTema;
       this.usuario = usuario;
       this.color = color;
       this.marcadors = marcadors;
    }
   
    public String getTipoTema() {
        return this.tipoTema;
    }
    
    public void setTipoTema(String tipoTema) {
        this.tipoTema = tipoTema;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Set getMarcadors() {
        return this.marcadors;
    }
    
    public void setMarcadors(Set marcadors) {
        this.marcadors = marcadors;
    }




}


